version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports:
      - "3306:3306"
