spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: root
    locations: classpath:/db/migration
    enabled: true
