CREATE TABLE USER (
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(30) UNIQUE,
    password CHAR(60) NOT NULL,
    created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    lock_version BIGINT UNSIGNED DEFAULT 0 NOT NULL,
    delete_flag BOOLEAN DEFAULT 0 NOT NULL
);

CREATE TABLE TAG (
    tag_id SERIAL PRIMARY KEY,
    name VARCHAR(15) UNIQUE
);

CREATE TABLE TODO (
    todo_id SERIAL PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    tag_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(30) NOT NULL,
    detail VARCHAR(200) NOT NULL,
    created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL,
    updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL,
    lock_version BIGINT UNSIGNED DEFAULT 0 NOT NULL,
    delete_flag BOOLEAN DEFAULT 0 NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER (user_id),
    FOREIGN KEY (tag_id) REFERENCES TAG (tag_id)
);